cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: 2025.1.1
  author_name: Dominic Fahey
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: Dominic Fahey Personal Blob
  docker_setup: default
  domain_name: dominicfahey.com
  email: domfahey@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: domfahey
  include_static_files: y
  marketing_email_platform: convert_kit
  plugin_chat_mode: llm
  plugins:
  - chat
  post_process: y
  project_name: Dominic Fahey Blog
  project_slug: dfaheyblog
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_auth: y
  use_api_keys: y
  use_async: n
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: n
  use_examples: y
  use_flowbite: y
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: y
  use_subscriptions: n
  use_teams: y
  use_teams_example: n
  use_translations: n
  use_wagtail: y
